import type { SeedTopic } from "./types";
import { arrays } from "./problems/arrays";
import { strings } from "./problems/strings";

// Full DSA taxonomy. Topics are seeded even when their problem set is still
// being authored, so the tree/structure is complete. Content is added in
// batches — `arrays` and `strings` are fully authored first.
export const dsaTopics: SeedTopic[] = [
  {
    slug: "arrays",
    name: "Arrays",
    description: "Traversals, prefix sums, in-place tricks, and the hash-map staples.",
    icon: "Brackets",
    order: 1,
    problems: arrays,
  },
  {
    slug: "strings",
    name: "Strings",
    description: "Two pointers, sliding windows, and frequency counting on text.",
    icon: "Type",
    order: 2,
    problems: strings,
  },
  {
    slug: "two-pointers",
    name: "Two Pointers",
    description: "Converging and fast/slow pointer techniques on sorted data.",
    icon: "MoveHorizontal",
    order: 3,
    problems: [],
  },
  {
    slug: "sliding-window",
    name: "Sliding Window",
    description: "Fixed and variable windows for subarray/substring problems.",
    icon: "RectangleHorizontal",
    order: 4,
    problems: [],
  },
  {
    slug: "binary-search",
    name: "Binary Search",
    description: "Search on sorted arrays and on the answer space.",
    icon: "Search",
    order: 5,
    problems: [],
  },
  {
    slug: "stacks-queues",
    name: "Stacks & Queues",
    description: "Monotonic stacks, queues, and expression parsing.",
    icon: "Layers",
    order: 6,
    problems: [],
  },
  {
    slug: "linked-list",
    name: "Linked Lists",
    description: "Pointer manipulation, cycle detection, and reversal.",
    icon: "Link2",
    order: 7,
    problems: [],
  },
  {
    slug: "trees",
    name: "Trees",
    description: "Binary trees, BSTs, traversals, and recursion.",
    icon: "GitFork",
    order: 8,
    problems: [],
  },
  {
    slug: "tries",
    name: "Tries",
    description: "Prefix trees for word and dictionary problems.",
    icon: "Network",
    order: 9,
    problems: [],
  },
  {
    slug: "heaps",
    name: "Heaps & Priority Queues",
    description: "Top-K, streaming medians, and scheduling with heaps.",
    icon: "TriangleRight",
    order: 10,
    problems: [],
  },
  {
    slug: "backtracking",
    name: "Backtracking",
    description: "Systematic search over subsets, permutations, and boards.",
    icon: "Undo2",
    order: 11,
    problems: [],
  },
  {
    slug: "graphs",
    name: "Graphs",
    description: "BFS, DFS, topological sort, and union-find.",
    icon: "Waypoints",
    order: 12,
    problems: [],
  },
  {
    slug: "greedy",
    name: "Greedy",
    description: "Locally optimal choices that yield global optima.",
    icon: "TrendingUp",
    order: 13,
    problems: [],
  },
  {
    slug: "dynamic-programming",
    name: "Dynamic Programming",
    description: "Memoization and tabulation over overlapping subproblems.",
    icon: "Boxes",
    order: 14,
    problems: [],
  },
  {
    slug: "bit-manipulation",
    name: "Bit Manipulation",
    description: "XOR tricks, masks, and counting bits.",
    icon: "Binary",
    order: 15,
    problems: [],
  },
];
